/* SPDX-License-Identifier: MIT */
/*
 * effect_schema.hpp - AUTO-GENERATED by policy/policy_ir.py.
 * C++ constants and helpers for the unified effect event model.
 */
#ifndef GHOSTBPF_OBSERV_EFFECT_SCHEMA_HPP
#define GHOSTBPF_OBSERV_EFFECT_SCHEMA_HPP

#include <cstdint>
#include <string>

namespace ghostbpf_observ {

/* ---- effect classes ---- */
inline constexpr uint8_t CLASS_FILESYSTEM = 1;
inline constexpr uint8_t CLASS_NETWORK = 2;
inline constexpr uint8_t CLASS_IPC = 3;
inline constexpr uint8_t CLASS_SIGNAL = 4;
inline constexpr uint8_t CLASS_PRIVILEGE = 5;
inline constexpr uint8_t CLASS_OUTPUT = 6;
inline constexpr uint8_t CLASS_SYSTEM = 7;

/* ---- operations per class ---- */
/* FILESYSTEM */
inline constexpr uint8_t OP_READ = 1;
inline constexpr uint8_t OP_WRITE = 2;
inline constexpr uint8_t OP_CREATE = 3;
inline constexpr uint8_t OP_DELETE = 4;
inline constexpr uint8_t OP_RENAME = 5;
inline constexpr uint8_t OP_LINK = 6;
inline constexpr uint8_t OP_SYMLINK = 7;
inline constexpr uint8_t OP_TRUNCATE = 8;
inline constexpr uint8_t OP_CHMOD = 9;
inline constexpr uint8_t OP_CHOWN = 10;
inline constexpr uint8_t OP_MKDIR = 11;
inline constexpr uint8_t OP_RMDIR = 12;

/* NETWORK */
inline constexpr uint8_t OP_CONNECT = 1;
inline constexpr uint8_t OP_BIND = 2;
inline constexpr uint8_t OP_SEND = 3;

/* IPC */
inline constexpr uint8_t OP_PIPE_WRITE = 1;
inline constexpr uint8_t OP_UNIX_WRITE = 2;
inline constexpr uint8_t OP_SYSV_SHM = 3;
inline constexpr uint8_t OP_SYSV_MSG = 4;
inline constexpr uint8_t OP_SYSV_SEM = 5;
inline constexpr uint8_t OP_POSIX_MQ = 6;
inline constexpr uint8_t OP_SHARED_MAPPING = 7;

/* SIGNAL */
inline constexpr uint8_t OP_KILL = 1;
inline constexpr uint8_t OP_PTRACE = 2;

/* PRIVILEGE */
inline constexpr uint8_t OP_EXEC_PRIV = 1;
inline constexpr uint8_t OP_SETUID = 2;
inline constexpr uint8_t OP_SETGID = 3;
inline constexpr uint8_t OP_SETGROUPS = 4;
inline constexpr uint8_t OP_CAPSET = 5;

/* OUTPUT */
inline constexpr uint8_t OP_WRITE_OUT = 1;
inline constexpr uint8_t OP_SENDFILE = 2;
inline constexpr uint8_t OP_SPLICE = 3;
inline constexpr uint8_t OP_IO_URING = 4;

/* SYSTEM */
inline constexpr uint8_t OP_MOUNT = 1;
inline constexpr uint8_t OP_NAMESPACE = 2;
inline constexpr uint8_t OP_KEYRING = 3;
inline constexpr uint8_t OP_BPF = 4;
inline constexpr uint8_t OP_PERF = 5;
inline constexpr uint8_t OP_TTY_IOCTL = 6;
inline constexpr uint8_t OP_PROCESS_VM = 7;

/* ---- sources ---- */
inline constexpr uint8_t SOURCE_FS = 0;
inline constexpr uint8_t SOURCE_PROC = 1;
inline constexpr uint8_t SOURCE_NET = 2;
inline constexpr uint8_t SOURCE_IPC = 3;
inline constexpr uint8_t SOURCE_PRIVILEGE = 4;
inline constexpr uint8_t SOURCE_OUTPUT = 5;
inline constexpr uint8_t SOURCE_SYSTEM = 6;

/* ---- encoding ---- */
inline constexpr uint16_t encode_event_type(uint8_t cls, uint8_t op) {
    return static_cast<uint16_t>(cls) | (static_cast<uint16_t>(op) << 8);
}
inline constexpr uint8_t event_class_of(uint16_t type) {
    return static_cast<uint8_t>(type & 0xFF);
}
inline constexpr uint8_t event_op_of(uint16_t type) {
    return static_cast<uint8_t>((type >> 8) & 0xFF);
}

/* ---- legacy aliases ---- */
inline constexpr uint16_t FS_EVENT_OPEN = encode_event_type(CLASS_FILESYSTEM, OP_READ);
inline constexpr uint16_t FS_EVENT_CREATE = encode_event_type(CLASS_FILESYSTEM, OP_CREATE);
inline constexpr uint16_t FS_EVENT_DELETE = encode_event_type(CLASS_FILESYSTEM, OP_DELETE);
inline constexpr uint16_t FS_EVENT_RENAME = encode_event_type(CLASS_FILESYSTEM, OP_RENAME);
inline constexpr uint16_t FS_EVENT_CHMOD = encode_event_type(CLASS_FILESYSTEM, OP_CHMOD);
inline constexpr uint16_t FS_EVENT_CHOWN = encode_event_type(CLASS_FILESYSTEM, OP_CHOWN);
inline constexpr uint16_t FS_EVENT_MKDIR = encode_event_type(CLASS_FILESYSTEM, OP_MKDIR);
inline constexpr uint16_t FS_EVENT_RMDIR = encode_event_type(CLASS_FILESYSTEM, OP_RMDIR);
inline constexpr uint16_t FS_EVENT_LINK = encode_event_type(CLASS_FILESYSTEM, OP_LINK);
inline constexpr uint16_t FS_EVENT_SYMLINK = encode_event_type(CLASS_FILESYSTEM, OP_SYMLINK);
inline constexpr uint16_t FS_EVENT_TRUNCATE = encode_event_type(CLASS_FILESYSTEM, OP_TRUNCATE);
inline constexpr uint16_t PROC_EVENT_EXEC = encode_event_type(CLASS_PRIVILEGE, OP_EXEC_PRIV);
inline constexpr uint16_t PROC_EVENT_EXEC_PRIV = encode_event_type(CLASS_PRIVILEGE, OP_EXEC_PRIV);
inline constexpr uint16_t PROC_EVENT_KILL = encode_event_type(CLASS_SIGNAL, OP_KILL);
inline constexpr uint16_t PROC_EVENT_PTRACE = encode_event_type(CLASS_SIGNAL, OP_PTRACE);
inline constexpr uint16_t PROC_EVENT_SETUID = encode_event_type(CLASS_PRIVILEGE, OP_SETUID);
inline constexpr uint16_t PROC_EVENT_SETGID = encode_event_type(CLASS_PRIVILEGE, OP_SETGID);
inline constexpr uint16_t PROC_EVENT_SETGROUPS = encode_event_type(CLASS_PRIVILEGE, OP_SETGROUPS);
inline constexpr uint16_t PROC_EVENT_CAPSET = encode_event_type(CLASS_PRIVILEGE, OP_CAPSET);
inline constexpr uint16_t PROC_EVENT_CONNECT = encode_event_type(CLASS_NETWORK, OP_CONNECT);
inline constexpr uint16_t PROC_EVENT_BIND = encode_event_type(CLASS_NETWORK, OP_BIND);
inline constexpr uint16_t PROC_EVENT_SEND = encode_event_type(CLASS_NETWORK, OP_SEND);
inline constexpr uint16_t PROC_EVENT_PIPE_WRITE = encode_event_type(CLASS_IPC, OP_PIPE_WRITE);
inline constexpr uint16_t PROC_EVENT_UNIX_WRITE = encode_event_type(CLASS_IPC, OP_UNIX_WRITE);
inline constexpr uint16_t PROC_EVENT_SHM = encode_event_type(CLASS_IPC, OP_SYSV_SHM);
inline constexpr uint16_t PROC_EVENT_MSG = encode_event_type(CLASS_IPC, OP_SYSV_MSG);
inline constexpr uint16_t PROC_EVENT_SEM = encode_event_type(CLASS_IPC, OP_SYSV_SEM);
inline constexpr uint16_t PROC_EVENT_MQ = encode_event_type(CLASS_IPC, OP_POSIX_MQ);
inline constexpr uint16_t PROC_EVENT_SHARED_MAPPING = encode_event_type(CLASS_IPC, OP_SHARED_MAPPING);
inline constexpr uint16_t PROC_EVENT_WRITE_OUT = encode_event_type(CLASS_OUTPUT, OP_WRITE_OUT);
inline constexpr uint16_t PROC_EVENT_SENDFILE = encode_event_type(CLASS_OUTPUT, OP_SENDFILE);
inline constexpr uint16_t PROC_EVENT_SPLICE = encode_event_type(CLASS_OUTPUT, OP_SPLICE);
inline constexpr uint16_t PROC_EVENT_IO_URING = encode_event_type(CLASS_OUTPUT, OP_IO_URING);
inline constexpr uint16_t PROC_EVENT_MOUNT = encode_event_type(CLASS_SYSTEM, OP_MOUNT);
inline constexpr uint16_t PROC_EVENT_UMOUNT = encode_event_type(CLASS_SYSTEM, OP_MOUNT);
inline constexpr uint16_t PROC_EVENT_UNSHARE = encode_event_type(CLASS_SYSTEM, OP_NAMESPACE);
inline constexpr uint16_t PROC_EVENT_SETNS = encode_event_type(CLASS_SYSTEM, OP_NAMESPACE);
inline constexpr uint16_t PROC_EVENT_KEYCTL = encode_event_type(CLASS_SYSTEM, OP_KEYRING);
inline constexpr uint16_t PROC_EVENT_ADD_KEY = encode_event_type(CLASS_SYSTEM, OP_KEYRING);
inline constexpr uint16_t PROC_EVENT_REQUEST_KEY = encode_event_type(CLASS_SYSTEM, OP_KEYRING);
inline constexpr uint16_t PROC_EVENT_BPF = encode_event_type(CLASS_SYSTEM, OP_BPF);
inline constexpr uint16_t PROC_EVENT_PERF_EVENT_OPEN = encode_event_type(CLASS_SYSTEM, OP_PERF);
inline constexpr uint16_t PROC_EVENT_TTY_IOCTL = encode_event_type(CLASS_SYSTEM, OP_TTY_IOCTL);
inline constexpr uint16_t PROC_EVENT_PROCESS_VM_READV = encode_event_type(CLASS_SYSTEM, OP_PROCESS_VM);
inline constexpr uint16_t PROC_EVENT_PROCESS_VM_WRITEV = encode_event_type(CLASS_SYSTEM, OP_PROCESS_VM);

/* ---- event name lookup ---- */
const char *effect_event_name(uint16_t event_type);

} // namespace ghostbpf_observ

#endif // GHOSTBPF_OBSERV_EFFECT_SCHEMA_HPP
