/* SPDX-License-Identifier: MIT */
/*
 * enforcer.cpp – whitelist eBPF LSM enforcer implementation.
 */
#include "ghostbpf-observ/enforcer.h"

#include "observ_common.h"
#include "enforce.skel.h"    /* generated by bpftool */

#include <bpf/libbpf.h>
#include <cstring>
#include <set>
#include <stdexcept>

namespace ghostbpf_observ {

/* BPF-side key structure (must match enforce.bpf.c) */
struct bpf_whitelist_key {
    uint64_t cgroup_id;
    uint16_t event_type;
    uint16_t _pad;
    char     path_prefix[MAX_PREFIX_LEN];
};

/* ===================================================================== */
/*  PIMPL                                                                */
/* ===================================================================== */

struct Enforcer::Impl {
    struct enforce_bpf *skel = nullptr;
    std::set<uint64_t> enforced_cgroups;

    ~Impl() {
        /* Disable all enforced cgroups before destroying */
        for (uint64_t cg : enforced_cgroups) {
            bpf_map__delete_elem(skel->maps.enforce_enabled,
                                 &cg, sizeof(cg), 0);
        }
        if (skel) enforce_bpf__destroy(skel);
    }
};

/* ===================================================================== */
/*  public API                                                           */
/* ===================================================================== */

Enforcer::Enforcer() : impl_(std::make_unique<Impl>()) {
    impl_->skel = enforce_bpf__open();
    if (!impl_->skel)
        throw std::runtime_error("enforce_bpf__open failed");

    if (enforce_bpf__load(impl_->skel))
        throw std::runtime_error("enforce_bpf__load failed");

    if (enforce_bpf__attach(impl_->skel))
        throw std::runtime_error("enforce_bpf__attach failed");
}

Enforcer::~Enforcer() = default;

Enforcer::Enforcer(Enforcer &&) noexcept            = default;
Enforcer &Enforcer::operator=(Enforcer &&) noexcept = default;

bool Enforcer::enable(uint64_t cgroup_id) {
    uint8_t one = 1;
    int err = bpf_map__update_elem(impl_->skel->maps.enforce_enabled,
                                   &cgroup_id, sizeof(cgroup_id),
                                   &one, sizeof(one), BPF_ANY);
    if (err) {
        fprintf(stderr, "[Enforcer] enable cgroup %lu failed (err=%d)\n",
                cgroup_id, err);
        return false;
    }
    impl_->enforced_cgroups.insert(cgroup_id);
    return true;
}

bool Enforcer::disable(uint64_t cgroup_id) {
    /* Remove from enforce_enabled map */
    bpf_map__delete_elem(impl_->skel->maps.enforce_enabled,
                         &cgroup_id, sizeof(cgroup_id), 0);
    impl_->enforced_cgroups.erase(cgroup_id);

    /* Clear all rules for this cgroup */
    clear_rules(cgroup_id);
    return true;
}

bool Enforcer::add_rule(const WhitelistRule &rule) {
    struct bpf_whitelist_key key = {};
    key.cgroup_id = rule.cgroup_id;
    key.event_type = rule.event_type;
    key._pad = 0;

    if (!rule.path_prefix.empty()) {
        size_t copy_len = rule.path_prefix.size();
        if (copy_len >= MAX_PREFIX_LEN) copy_len = MAX_PREFIX_LEN - 1;
        std::memcpy(key.path_prefix, rule.path_prefix.c_str(), copy_len);
    }

    uint8_t one = 1;
    int err = bpf_map__update_elem(impl_->skel->maps.whitelist_rules,
                                   &key, sizeof(key),
                                   &one, sizeof(one), BPF_ANY);
    if (err) {
        fprintf(stderr, "[Enforcer] add_rule failed (err=%d)\n", err);
        return false;
    }
    return true;
}

size_t Enforcer::add_rules(const std::vector<WhitelistRule> &rules) {
    size_t count = 0;
    for (const auto &rule : rules) {
        if (add_rule(rule)) count++;
    }
    return count;
}

bool Enforcer::clear_rules(uint64_t cgroup_id) {
    /* Iterate whitelist_rules map and delete all entries for this cgroup.
     * BPF map iteration: get_next_key from NULL, delete matching entries. */
    struct bpf_whitelist_key key = {}, next_key = {};

    /* Collect keys to delete (cannot delete while iterating) */
    std::vector<struct bpf_whitelist_key> to_delete;

    int ret = bpf_map__get_next_key(impl_->skel->maps.whitelist_rules,
                                    NULL, &next_key, sizeof(next_key));
    while (ret == 0) {
        if (next_key.cgroup_id == cgroup_id) {
            to_delete.push_back(next_key);
        }
        key = next_key;
        ret = bpf_map__get_next_key(impl_->skel->maps.whitelist_rules,
                                    &key, &next_key, sizeof(next_key));
    }

    for (auto &k : to_delete) {
        bpf_map__delete_elem(impl_->skel->maps.whitelist_rules,
                             &k, sizeof(k), 0);
    }

    return true;
}

bool Enforcer::is_enforcing(uint64_t cgroup_id) const {
    return impl_->enforced_cgroups.count(cgroup_id) > 0;
}

} // namespace ghostbpf_observ
