/* SPDX-License-Identifier: MIT */
/*
 * observer.cpp – unified Observer implementation (FS + PROC events).
 */
#include "ghostbpf-observ/observer.h"

#include "observ_common.h"
#include "observ.skel.h"       /* generated by bpftool */

#include <bpf/libbpf.h>
#include <cerrno>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>

namespace ghostbpf_observ {

/* ===================================================================== */
/*  JSON-line helpers                                                    */
/* ===================================================================== */

static std::string json_escape(const std::string &s) {
    std::string out;
    out.reserve(s.size() + 4);
    for (unsigned char c : s) {
        switch (c) {
        case '"':  out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\n': out += "\\n";  break;
        case '\r': out += "\\r";  break;
        case '\t': out += "\\t";  break;
        default:
            if (c < 0x20) {
                out += "\\u00";
                out += "0123456789abcdef"[c >> 4];
                out += "0123456789abcdef"[c & 0xf];
            } else {
                out += static_cast<char>(c);
            }
        }
    }
    return out;
}

static const char *event_type_name(uint16_t event_type) {
    switch (event_type) {
    /* FS events */
    case FS_EVENT_OPEN:     return "OPEN";
    case FS_EVENT_CREATE:   return "CREATE";
    case FS_EVENT_DELETE:   return "DELETE";
    case FS_EVENT_RENAME:   return "RENAME";
    case FS_EVENT_CHMOD:    return "CHMOD";
    case FS_EVENT_CHOWN:    return "CHOWN";
    case FS_EVENT_MKDIR:    return "MKDIR";
    case FS_EVENT_RMDIR:    return "RMDIR";
    case FS_EVENT_LINK:     return "LINK";
    case FS_EVENT_SYMLINK:  return "SYMLINK";
    case FS_EVENT_TRUNCATE: return "TRUNCATE";
    /* PROC events */
    case PROC_EVENT_EXEC:   return "EXEC";
    case PROC_EVENT_FORK:   return "FORK";
    case PROC_EVENT_EXIT:   return "EXIT";
    case PROC_EVENT_KILL:   return "KILL";
    case PROC_EVENT_PRCTL:  return "PRCTL";
    case PROC_EVENT_PTRACE: return "PTRACE";
    case PROC_EVENT_SETUID: return "SETUID";
    case PROC_EVENT_CAPSET: return "CAPSET";
    default:                return "UNKNOWN";
    }
}

static std::string evt_to_json(const struct observ_event &e) {
    std::ostringstream s;
    s << std::dec;
    s << "{\"ts\":"            << e.timestamp_ns
      << ",\"pid\":"           << e.pid
      << ",\"tid\":"           << e.tid
      << ",\"uid\":"           << e.uid
      << ",\"gid\":"           << e.gid
      << ",\"cgroup_id\":"     << e.cgroup_id
      << ",\"event\":\""       << event_type_name(e.event_type) << "\""
      << ",\"arg1\":"          << e.arg1
      << ",\"arg2\":"          << e.arg2
      << ",\"arg3\":"          << e.arg3
      << ",\"comm\":\""        << json_escape(e.comm) << "\""
      << ",\"path\":\""        << json_escape(e.path) << "\""
      << ",\"new_path\":\""    << json_escape(e.new_path) << "\""
      << "}\n";
    return s.str();
}

/* ===================================================================== */
/*  PIMPL                                                                */
/* ===================================================================== */

struct Observer::Impl {
    struct observ_bpf *skel = nullptr;
    struct ring_buffer *rb  = nullptr;
    std::ofstream       log_file;
    uint64_t            cgroup_id = 0;
    bool                running   = false;
    bool                write_error = false;   /* a log write/flush failed */

    ~Impl() {
        if (running) {
            bpf_map__delete_elem(skel->maps.cgroup_monitor,
                                 &cgroup_id, sizeof(cgroup_id), 0);
            running = false;
        }
        if (rb)   ring_buffer__free(rb);
        if (skel) observ_bpf__destroy(skel);
    }

    /* Read the BPF ring-buffer overflow counter (dropped[0]). */
    uint64_t read_dropped() {
        if (!skel) return 0;
        __u32 key = 0;
        __u64 val = 0;
        if (bpf_map__lookup_elem(skel->maps.dropped,
                                 &key, sizeof(key),
                                 &val, sizeof(val), 0) != 0)
            return 0;
        return val;
    }

    static int handle_event(void *ctx, void *data, size_t /*data_sz*/) {
        auto *impl = static_cast<Impl *>(ctx);
        auto &evt  = *static_cast<struct observ_event *>(data);
        impl->log_file << evt_to_json(evt);
        impl->log_file.flush();
        /* A failed write/flush means the on-disk log is missing this event:
         * remember it so stop() can fail the epoch closed. */
        if (!impl->log_file)
            impl->write_error = true;
        return 0;
    }
};

/* ===================================================================== */
/*  public API                                                           */
/* ===================================================================== */

Observer::Observer() : impl_(std::make_unique<Impl>()) {
    impl_->skel = observ_bpf__open();
    if (!impl_->skel)
        throw std::runtime_error("observ_bpf__open failed");

    if (observ_bpf__load(impl_->skel))
        throw std::runtime_error("observ_bpf__load failed");

    if (observ_bpf__attach(impl_->skel))
        throw std::runtime_error("observ_bpf__attach failed");
}

Observer::~Observer() = default;

Observer::Observer(Observer &&) noexcept            = default;
Observer &Observer::operator=(Observer &&) noexcept = default;

bool Observer::start(uint64_t cgroup_id, const std::string &output_path) {
    if (impl_->running) stop();

    /* Reset the per-epoch integrity state and drop counter. */
    impl_->write_error = false;
    {
        __u32 key = 0;
        __u64 zero = 0;
        bpf_map__update_elem(impl_->skel->maps.dropped,
                             &key, sizeof(key), &zero, sizeof(zero), BPF_ANY);
    }

    __u8 one = 1;
    int err = bpf_map__update_elem(impl_->skel->maps.cgroup_monitor,
                                   &cgroup_id, sizeof(cgroup_id),
                                   &one, sizeof(one), BPF_ANY);
    if (err) {
        fprintf(stderr, "[Observer] cgroup_monitor update failed (err=%d)\n", err);
        return false;
    }

    impl_->log_file.open(output_path, std::ios::out | std::ios::trunc);
    if (!impl_->log_file) {
        fprintf(stderr, "[Observer] cannot open %s\n", output_path.c_str());
        bpf_map__delete_elem(impl_->skel->maps.cgroup_monitor,
                             &cgroup_id, sizeof(cgroup_id), 0);
        return false;
    }

    impl_->rb = ring_buffer__new(
        bpf_map__fd(impl_->skel->maps.events),
        Impl::handle_event, impl_.get(), nullptr);
    if (!impl_->rb) {
        fprintf(stderr, "[Observer] ring_buffer__new failed\n");
        bpf_map__delete_elem(impl_->skel->maps.cgroup_monitor,
                             &cgroup_id, sizeof(cgroup_id), 0);
        return false;
    }

    impl_->cgroup_id = cgroup_id;
    impl_->running    = true;
    return true;
}

void Observer::poll(int timeout_ms) {
    if (!impl_->running || !impl_->rb) return;
    ring_buffer__poll(impl_->rb, timeout_ms);
}

IntegrityReport Observer::stop() {
    IntegrityReport rep;
    if (!impl_->running) return rep;

    /* 1. Stop the source of new events FIRST: unmonitor the cgroup so no
     *    further syscalls reserve ring-buffer slots. (Callers freeze the
     *    workload before stop, so this quiesces the event stream.) */
    bpf_map__delete_elem(impl_->skel->maps.cgroup_monitor,
                         &impl_->cgroup_id, sizeof(impl_->cgroup_id), 0);

    /* 2. DRAIN the ring buffer to empty so tail events already queued are
     *    written to the log before we seal it. ring_buffer__consume returns
     *    the number of records processed (0 when empty, <0 on error). */
    if (impl_->rb) {
        for (;;) {
            int n = ring_buffer__consume(impl_->rb);
            if (n < 0) { rep.drain_error = true; break; }
            if (n == 0) break;
        }
        ring_buffer__free(impl_->rb);
        impl_->rb = nullptr;
    }

    /* 3. Flush + close the log, detecting any write failure. */
    impl_->log_file.flush();
    if (!impl_->log_file) impl_->write_error = true;
    impl_->log_file.close();

    /* 4. Read the BPF drop counter and compose the completeness verdict. */
    rep.dropped_events = impl_->read_dropped();
    rep.write_error    = impl_->write_error;
    rep.complete = (rep.dropped_events == 0) && !rep.write_error && !rep.drain_error;
    if (!rep.complete) {
        std::ostringstream r;
        r << "incomplete log:";
        if (rep.dropped_events) r << " dropped_events=" << rep.dropped_events;
        if (rep.write_error)    r << " write_error";
        if (rep.drain_error)    r << " drain_error";
        rep.reason = r.str();
        fprintf(stderr, "[Observer] %s (cgroup=%lu)\n",
                rep.reason.c_str(), (unsigned long)impl_->cgroup_id);
    }

    impl_->running = false;
    return rep;
}

bool Observer::is_running() const { return impl_->running; }

} // namespace ghostbpf_observ
