/* SPDX-License-Identifier: MIT */
/*
 * observer.cpp – unified Observer implementation (FS + PROC events).
 */
#include "ghostbpf-observ/observer.h"

#include "observ_common.h"
#include "observ.skel.h"       /* generated by bpftool */

#include <bpf/libbpf.h>
#include <cerrno>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>

namespace ghostbpf_observ {

/* ===================================================================== */
/*  JSON-line helpers                                                    */
/* ===================================================================== */

static std::string json_escape(const std::string &s) {
    std::string out;
    out.reserve(s.size() + 4);
    for (unsigned char c : s) {
        switch (c) {
        case '"':  out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\n': out += "\\n";  break;
        case '\r': out += "\\r";  break;
        case '\t': out += "\\t";  break;
        default:
            if (c < 0x20) {
                out += "\\u00";
                out += "0123456789abcdef"[c >> 4];
                out += "0123456789abcdef"[c & 0xf];
            } else {
                out += static_cast<char>(c);
            }
        }
    }
    return out;
}

static const char *event_type_name(uint16_t event_type) {
    switch (event_type) {
    /* FS events */
    case FS_EVENT_OPEN:     return "OPEN";
    case FS_EVENT_CREATE:   return "CREATE";
    case FS_EVENT_DELETE:   return "DELETE";
    case FS_EVENT_RENAME:   return "RENAME";
    case FS_EVENT_CHMOD:    return "CHMOD";
    case FS_EVENT_CHOWN:    return "CHOWN";
    case FS_EVENT_MKDIR:    return "MKDIR";
    case FS_EVENT_RMDIR:    return "RMDIR";
    case FS_EVENT_LINK:     return "LINK";
    case FS_EVENT_SYMLINK:  return "SYMLINK";
    case FS_EVENT_TRUNCATE: return "TRUNCATE";
    /* PROC events */
    case PROC_EVENT_EXEC:   return "EXEC";
    case PROC_EVENT_FORK:   return "FORK";
    case PROC_EVENT_EXIT:   return "EXIT";
    case PROC_EVENT_KILL:   return "KILL";
    case PROC_EVENT_PRCTL:  return "PRCTL";
    case PROC_EVENT_PTRACE: return "PTRACE";
    case PROC_EVENT_SETUID: return "SETUID";
    case PROC_EVENT_CAPSET: return "CAPSET";
    default:                return "UNKNOWN";
    }
}

static std::string evt_to_json(const struct observ_event &e) {
    std::ostringstream s;
    s << std::dec;
    s << "{\"ts\":"            << e.timestamp_ns
      << ",\"pid\":"           << e.pid
      << ",\"tid\":"           << e.tid
      << ",\"uid\":"           << e.uid
      << ",\"gid\":"           << e.gid
      << ",\"cgroup_id\":"     << e.cgroup_id
      << ",\"event\":\""       << event_type_name(e.event_type) << "\""
      << ",\"arg1\":"          << e.arg1
      << ",\"arg2\":"          << e.arg2
      << ",\"arg3\":"          << e.arg3
      << ",\"comm\":\""        << json_escape(e.comm) << "\""
      << ",\"path\":\""        << json_escape(e.path) << "\""
      << ",\"new_path\":\""    << json_escape(e.new_path) << "\""
      << "}\n";
    return s.str();
}

/* ===================================================================== */
/*  PIMPL                                                                */
/* ===================================================================== */

struct Observer::Impl {
    struct observ_bpf *skel = nullptr;
    struct ring_buffer *rb  = nullptr;
    std::ofstream       log_file;
    uint64_t            cgroup_id = 0;
    bool                running   = false;

    ~Impl() {
        if (running) {
            bpf_map__delete_elem(skel->maps.cgroup_monitor,
                                 &cgroup_id, sizeof(cgroup_id), 0);
            running = false;
        }
        if (rb)   ring_buffer__free(rb);
        if (skel) observ_bpf__destroy(skel);
    }

    static int handle_event(void *ctx, void *data, size_t /*data_sz*/) {
        auto *impl = static_cast<Impl *>(ctx);
        auto &evt  = *static_cast<struct observ_event *>(data);
        impl->log_file << evt_to_json(evt);
        impl->log_file.flush();
        return 0;
    }
};

/* ===================================================================== */
/*  public API                                                           */
/* ===================================================================== */

Observer::Observer() : impl_(std::make_unique<Impl>()) {
    impl_->skel = observ_bpf__open();
    if (!impl_->skel)
        throw std::runtime_error("observ_bpf__open failed");

    if (observ_bpf__load(impl_->skel))
        throw std::runtime_error("observ_bpf__load failed");

    if (observ_bpf__attach(impl_->skel))
        throw std::runtime_error("observ_bpf__attach failed");
}

Observer::~Observer() = default;

Observer::Observer(Observer &&) noexcept            = default;
Observer &Observer::operator=(Observer &&) noexcept = default;

bool Observer::start(uint64_t cgroup_id, const std::string &output_path) {
    if (impl_->running) stop();

    __u8 one = 1;
    int err = bpf_map__update_elem(impl_->skel->maps.cgroup_monitor,
                                   &cgroup_id, sizeof(cgroup_id),
                                   &one, sizeof(one), BPF_ANY);
    if (err) {
        fprintf(stderr, "[Observer] cgroup_monitor update failed (err=%d)\n", err);
        return false;
    }

    impl_->log_file.open(output_path, std::ios::out | std::ios::trunc);
    if (!impl_->log_file) {
        fprintf(stderr, "[Observer] cannot open %s\n", output_path.c_str());
        bpf_map__delete_elem(impl_->skel->maps.cgroup_monitor,
                             &cgroup_id, sizeof(cgroup_id), 0);
        return false;
    }

    impl_->rb = ring_buffer__new(
        bpf_map__fd(impl_->skel->maps.events),
        Impl::handle_event, impl_.get(), nullptr);
    if (!impl_->rb) {
        fprintf(stderr, "[Observer] ring_buffer__new failed\n");
        bpf_map__delete_elem(impl_->skel->maps.cgroup_monitor,
                             &cgroup_id, sizeof(cgroup_id), 0);
        return false;
    }

    impl_->cgroup_id = cgroup_id;
    impl_->running    = true;
    return true;
}

void Observer::poll(int timeout_ms) {
    if (!impl_->running || !impl_->rb) return;
    ring_buffer__poll(impl_->rb, timeout_ms);
}

void Observer::stop() {
    if (!impl_->running) return;

    bpf_map__delete_elem(impl_->skel->maps.cgroup_monitor,
                         &impl_->cgroup_id, sizeof(impl_->cgroup_id), 0);
    ring_buffer__free(impl_->rb);
    impl_->rb = nullptr;
    impl_->log_file.close();
    impl_->running = false;
}

bool Observer::is_running() const { return impl_->running; }

} // namespace ghostbpf_observ
