//! AUTO-GENERATED by policy/policy_ir.py.
//! Unified effect event schema constants for ShadowProc.

#![allow(dead_code)]

/* ---- effect classes ---- */
pub const CLASS_FILESYSTEM: u8 = 1;
pub const CLASS_NETWORK: u8 = 2;
pub const CLASS_IPC: u8 = 3;
pub const CLASS_SIGNAL: u8 = 4;
pub const CLASS_PRIVILEGE: u8 = 5;
pub const CLASS_OUTPUT: u8 = 6;
pub const CLASS_SYSTEM: u8 = 7;

/* ---- operations per class ---- */
// FILESYSTEM
pub const OP_READ: u8 = 1;
pub const OP_WRITE: u8 = 2;
pub const OP_CREATE: u8 = 3;
pub const OP_DELETE: u8 = 4;
pub const OP_RENAME: u8 = 5;
pub const OP_LINK: u8 = 6;
pub const OP_SYMLINK: u8 = 7;
pub const OP_TRUNCATE: u8 = 8;
pub const OP_CHMOD: u8 = 9;
pub const OP_CHOWN: u8 = 10;
pub const OP_MKDIR: u8 = 11;
pub const OP_RMDIR: u8 = 12;

// NETWORK
pub const OP_CONNECT: u8 = 1;
pub const OP_BIND: u8 = 2;
pub const OP_SEND: u8 = 3;

// IPC
pub const OP_PIPE_WRITE: u8 = 1;
pub const OP_UNIX_WRITE: u8 = 2;
pub const OP_SYSV_SHM: u8 = 3;
pub const OP_SYSV_MSG: u8 = 4;
pub const OP_SYSV_SEM: u8 = 5;
pub const OP_POSIX_MQ: u8 = 6;
pub const OP_SHARED_MAPPING: u8 = 7;

// SIGNAL
pub const OP_KILL: u8 = 1;
pub const OP_PTRACE: u8 = 2;

// PRIVILEGE
pub const OP_EXEC_PRIV: u8 = 1;
pub const OP_SETUID: u8 = 2;
pub const OP_SETGID: u8 = 3;
pub const OP_SETGROUPS: u8 = 4;
pub const OP_CAPSET: u8 = 5;

// OUTPUT
pub const OP_WRITE_OUT: u8 = 1;
pub const OP_SENDFILE: u8 = 2;
pub const OP_SPLICE: u8 = 3;
pub const OP_IO_URING: u8 = 4;

// SYSTEM
pub const OP_MOUNT: u8 = 1;
pub const OP_NAMESPACE: u8 = 2;
pub const OP_KEYRING: u8 = 3;
pub const OP_BPF: u8 = 4;
pub const OP_PERF: u8 = 5;
pub const OP_TTY_IOCTL: u8 = 6;
pub const OP_PROCESS_VM: u8 = 7;

/* ---- sources ---- */
pub const SOURCE_FS: u8 = 0;
pub const SOURCE_PROC: u8 = 1;
pub const SOURCE_NET: u8 = 2;
pub const SOURCE_IPC: u8 = 3;
pub const SOURCE_PRIVILEGE: u8 = 4;
pub const SOURCE_OUTPUT: u8 = 5;
pub const SOURCE_SYSTEM: u8 = 6;

/* ---- encoding ---- */
pub fn encode_event_type(cls: u8, op: u8) -> u16 {
    (cls as u16) | ((op as u16) << 8)
}
pub fn event_class_of(ty: u16) -> u8 {
    (ty & 0xFF) as u8
}
pub fn event_op_of(ty: u16) -> u8 {
    ((ty >> 8) & 0xFF) as u8
}

/* ---- epoch modes (Phase 2) ---- */
pub const MODE_SPECULATIVE: u8 = 0;
pub const MODE_AUTHORIZED_PENDING: u8 = 1;
pub const MODE_ENFORCED: u8 = 2;

pub const DECISION_ALLOW: u8 = 0;
pub const DECISION_FENCE: u8 = 1;
pub const DECISION_DENY: u8 = 2;
