/* SPDX-License-Identifier: GPL-2.0 */
/*
 * effect_schema.h - AUTO-GENERATED by policy/policy_ir.py.
 * Unified effect event schema for Speculative Shadow.
 *
 * Defines the (effect_class, operation) model that replaces the two
 * colliding event numbering schemes (FS_EVENT_*, PROC_EVENT_* and
 * ShadowProc EVENT_*). All BPF programs and userspace components
 * include this header to share identical constant definitions.
 *
 * Encoding: event_type = effect_class | (operation << 8)
 *   - effect_class is the low byte (1-6)
 *   - operation is the high byte (1-12)
 *   - 0xFFFF = wildcard (any event)
 *   - -1 = wildcard (audit engine, int)
 */
#ifndef EFFECT_SCHEMA_H
#define EFFECT_SCHEMA_H

#ifndef __VMLINUX_H__
#include <linux/types.h>
#endif

/* ---- constants ------------------------------------------------------ */

#define MAX_PATH        256
#define MAX_COMM        16
#define MAX_ARGS        640
#define RING_BUF_SIZE   (512 * 1024)

/* ---- audit actions -------------------------------------------------- */

#define AUDIT_DENY  0
#define AUDIT_ALLOW 1

/* ---- event flags (arg3, FS events only) ------------------------------ */
/*
 * Set by the observer when cri_build_path() failed for this event
 * (path buffer emptied); consumers must treat the event's path as
 * unreliable and count it against audit completeness.
 */
#define OBSERV_FL_PATH_ERROR 0x1u

/* ---- effect classes ------------------------------------------------- */
#define EFFECT_CLASS_FILESYSTEM  1
#define EFFECT_CLASS_NETWORK  2
#define EFFECT_CLASS_IPC  3
#define EFFECT_CLASS_SIGNAL  4
#define EFFECT_CLASS_PRIVILEGE  5
#define EFFECT_CLASS_OUTPUT  6
#define EFFECT_CLASS_SYSTEM  7

/* ---- operations per class ------------------------------------------- */
/* FILESYSTEM */
#define EFFECT_OP_READ  1
#define EFFECT_OP_WRITE  2
#define EFFECT_OP_CREATE  3
#define EFFECT_OP_DELETE  4
#define EFFECT_OP_RENAME  5
#define EFFECT_OP_LINK  6
#define EFFECT_OP_SYMLINK  7
#define EFFECT_OP_TRUNCATE  8
#define EFFECT_OP_CHMOD  9
#define EFFECT_OP_CHOWN  10
#define EFFECT_OP_MKDIR  11
#define EFFECT_OP_RMDIR  12

/* NETWORK */
#define EFFECT_OP_CONNECT  1
#define EFFECT_OP_BIND  2
#define EFFECT_OP_SEND  3

/* IPC */
#define EFFECT_OP_PIPE_WRITE  1
#define EFFECT_OP_UNIX_WRITE  2
#define EFFECT_OP_SYSV_SHM  3
#define EFFECT_OP_SYSV_MSG  4
#define EFFECT_OP_SYSV_SEM  5
#define EFFECT_OP_POSIX_MQ  6
#define EFFECT_OP_SHARED_MAPPING  7

/* SIGNAL */
#define EFFECT_OP_KILL  1
#define EFFECT_OP_PTRACE  2

/* PRIVILEGE */
#define EFFECT_OP_EXEC_PRIV  1
#define EFFECT_OP_SETUID  2
#define EFFECT_OP_SETGID  3
#define EFFECT_OP_SETGROUPS  4
#define EFFECT_OP_CAPSET  5

/* OUTPUT */
#define EFFECT_OP_WRITE_OUT  1
#define EFFECT_OP_SENDFILE  2
#define EFFECT_OP_SPLICE  3
#define EFFECT_OP_IO_URING  4

/* SYSTEM */
#define EFFECT_OP_MOUNT  1
#define EFFECT_OP_NAMESPACE  2
#define EFFECT_OP_KEYRING  3
#define EFFECT_OP_BPF  4
#define EFFECT_OP_PERF  5
#define EFFECT_OP_TTY_IOCTL  6
#define EFFECT_OP_PROCESS_VM  7

/* ---- event sources ------------------------------------------------- */
#define EFFECT_SOURCE_FS  0
#define EFFECT_SOURCE_PROC  1
#define EFFECT_SOURCE_NET  2
#define EFFECT_SOURCE_IPC  3
#define EFFECT_SOURCE_PRIVILEGE  4
#define EFFECT_SOURCE_OUTPUT  5
#define EFFECT_SOURCE_SYSTEM  6

/* ---- encoding macro ------------------------------------------------- */
/*
 * Encode (effect_class, operation) into a single uint16 event_type.
 * Layout: low byte = effect_class, high byte = operation.
 * This matches the anonymous-union overlay in struct effect_event.
 */
#define EFFECT_EVENT_TYPE(cls, op) ((__u16)(cls) | ((__u16)(op) << 8))

/* ---- legacy event type aliases ------------------------------------- */
/* These map the old FS_EVENT_*, PROC_EVENT_* names to the new encoding. */
#define FS_EVENT_OPEN  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_READ)
#define FS_EVENT_CREATE  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_CREATE)
#define FS_EVENT_DELETE  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_DELETE)
#define FS_EVENT_RENAME  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_RENAME)
#define FS_EVENT_CHMOD  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_CHMOD)
#define FS_EVENT_CHOWN  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_CHOWN)
#define FS_EVENT_MKDIR  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_MKDIR)
#define FS_EVENT_RMDIR  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_RMDIR)
#define FS_EVENT_LINK  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_LINK)
#define FS_EVENT_SYMLINK  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_SYMLINK)
#define FS_EVENT_TRUNCATE  EFFECT_EVENT_TYPE(EFFECT_CLASS_FILESYSTEM, EFFECT_OP_TRUNCATE)
#define PROC_EVENT_EXEC  EFFECT_EVENT_TYPE(EFFECT_CLASS_PRIVILEGE, EFFECT_OP_EXEC_PRIV)
#define PROC_EVENT_EXEC_PRIV  EFFECT_EVENT_TYPE(EFFECT_CLASS_PRIVILEGE, EFFECT_OP_EXEC_PRIV)
#define PROC_EVENT_KILL  EFFECT_EVENT_TYPE(EFFECT_CLASS_SIGNAL, EFFECT_OP_KILL)
#define PROC_EVENT_PTRACE  EFFECT_EVENT_TYPE(EFFECT_CLASS_SIGNAL, EFFECT_OP_PTRACE)
#define PROC_EVENT_SETUID  EFFECT_EVENT_TYPE(EFFECT_CLASS_PRIVILEGE, EFFECT_OP_SETUID)
#define PROC_EVENT_SETGID  EFFECT_EVENT_TYPE(EFFECT_CLASS_PRIVILEGE, EFFECT_OP_SETGID)
#define PROC_EVENT_SETGROUPS  EFFECT_EVENT_TYPE(EFFECT_CLASS_PRIVILEGE, EFFECT_OP_SETGROUPS)
#define PROC_EVENT_CAPSET  EFFECT_EVENT_TYPE(EFFECT_CLASS_PRIVILEGE, EFFECT_OP_CAPSET)
#define PROC_EVENT_CONNECT  EFFECT_EVENT_TYPE(EFFECT_CLASS_NETWORK, EFFECT_OP_CONNECT)
#define PROC_EVENT_BIND  EFFECT_EVENT_TYPE(EFFECT_CLASS_NETWORK, EFFECT_OP_BIND)
#define PROC_EVENT_SEND  EFFECT_EVENT_TYPE(EFFECT_CLASS_NETWORK, EFFECT_OP_SEND)
#define PROC_EVENT_PIPE_WRITE  EFFECT_EVENT_TYPE(EFFECT_CLASS_IPC, EFFECT_OP_PIPE_WRITE)
#define PROC_EVENT_UNIX_WRITE  EFFECT_EVENT_TYPE(EFFECT_CLASS_IPC, EFFECT_OP_UNIX_WRITE)
#define PROC_EVENT_SHM  EFFECT_EVENT_TYPE(EFFECT_CLASS_IPC, EFFECT_OP_SYSV_SHM)
#define PROC_EVENT_MSG  EFFECT_EVENT_TYPE(EFFECT_CLASS_IPC, EFFECT_OP_SYSV_MSG)
#define PROC_EVENT_SEM  EFFECT_EVENT_TYPE(EFFECT_CLASS_IPC, EFFECT_OP_SYSV_SEM)
#define PROC_EVENT_MQ  EFFECT_EVENT_TYPE(EFFECT_CLASS_IPC, EFFECT_OP_POSIX_MQ)
#define PROC_EVENT_SHARED_MAPPING  EFFECT_EVENT_TYPE(EFFECT_CLASS_IPC, EFFECT_OP_SHARED_MAPPING)
#define PROC_EVENT_WRITE_OUT  EFFECT_EVENT_TYPE(EFFECT_CLASS_OUTPUT, EFFECT_OP_WRITE_OUT)
#define PROC_EVENT_SENDFILE  EFFECT_EVENT_TYPE(EFFECT_CLASS_OUTPUT, EFFECT_OP_SENDFILE)
#define PROC_EVENT_SPLICE  EFFECT_EVENT_TYPE(EFFECT_CLASS_OUTPUT, EFFECT_OP_SPLICE)
#define PROC_EVENT_IO_URING  EFFECT_EVENT_TYPE(EFFECT_CLASS_OUTPUT, EFFECT_OP_IO_URING)
#define PROC_EVENT_MOUNT  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_MOUNT)
#define PROC_EVENT_UMOUNT  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_MOUNT)
#define PROC_EVENT_UNSHARE  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_NAMESPACE)
#define PROC_EVENT_SETNS  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_NAMESPACE)
#define PROC_EVENT_KEYCTL  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_KEYRING)
#define PROC_EVENT_ADD_KEY  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_KEYRING)
#define PROC_EVENT_REQUEST_KEY  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_KEYRING)
#define PROC_EVENT_BPF  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_BPF)
#define PROC_EVENT_PERF_EVENT_OPEN  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_PERF)
#define PROC_EVENT_TTY_IOCTL  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_TTY_IOCTL)
#define PROC_EVENT_PROCESS_VM_READV  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_PROCESS_VM)
#define PROC_EVENT_PROCESS_VM_WRITEV  EFFECT_EVENT_TYPE(EFFECT_CLASS_SYSTEM, EFFECT_OP_PROCESS_VM)

/* ---- legacy unmapped events (process lifecycle, not effects) ------- */
#define PROC_EVENT_FORK  101
#define PROC_EVENT_EXIT  102
#define PROC_EVENT_PRCTL  104

/* ---- unified event struct (ring-buffer compatible) ------------------ */
/*
 * effect_event replaces observ_event. The anonymous union lets code
 * access either the combined event_type or the split (effect_class,
 * operation) fields. The source field (new) identifies which subsystem
 * originated the event.
 *
 * Field semantics:
 *   effect_class  = EFFECT_CLASS_FILESYSTEM / NETWORK / IPC / ...
 *   operation     = EFFECT_OP_READ / CREATE / CONNECT / ...
 *   source        = EFFECT_SOURCE_FS / PROC / NET / ...
 *   arg1          = flags(open) / mode(chmod,mkdir) / pid(kill) / ...
 *   arg2          = signal(kill) / target_pid(ptrace) / euid / ...
 *   arg3          = suid / tgid(tgkill) / ...
 *   path          = primary resource (file path, exec filename, ...)
 *   new_path      = secondary resource (rename dst, link target, ...)
 */
struct observ_event {
    __u64 timestamp_ns;
    __u32 pid;
    __u32 tid;
    __u32 uid;
    __u32 gid;
    __u64 cgroup_id;
    __u64 seq;              /* monotonic per-cgroup sequence */
    union {
        __u16 event_type;   /* legacy combined type */
        struct {
            __u8 effect_class;  /* EFFECT_CLASS_* */
            __u8 operation;     /* EFFECT_OP_* */
        };
    };
    __u8  source;           /* EFFECT_SOURCE_* */
    __u8  _pad0;
    __u32 arg1;
    __u32 arg2;
    __u32 arg3;
    __u32 _pad1;
    char  comm[MAX_COMM];
    char  path[MAX_PATH];         /* primary resource */
    char  new_path[MAX_PATH];     /* secondary resource */
};

/* Unified name: effect_event is an alias for observ_event. */
typedef struct observ_event effect_event;

/* ---- audit rule (userspace only) ----------------------------------- */

struct audit_rule {
    int  event_type;              /* encoded, or -1 for any */
    int  action;                  /* AUDIT_ALLOW or AUDIT_DENY */
    char path_pattern[MAX_PATH];  /* prefix to match */
};

#endif /* EFFECT_SCHEMA_H */
