// Code generated by policy/policy_ir.py. DO NOT EDIT.

package backend

/* ---- effect classes ---- */
const EffectClassFilesystem uint8 = 1
const EffectClassNetwork uint8 = 2
const EffectClassIpc uint8 = 3
const EffectClassSignal uint8 = 4
const EffectClassPrivilege uint8 = 5
const EffectClassOutput uint8 = 6
const EffectClassSystem uint8 = 7

/* ---- operations per class ---- */
// FILESYSTEM
const EffectOpRead uint8 = 1
const EffectOpWrite uint8 = 2
const EffectOpCreate uint8 = 3
const EffectOpDelete uint8 = 4
const EffectOpRename uint8 = 5
const EffectOpLink uint8 = 6
const EffectOpSymlink uint8 = 7
const EffectOpTruncate uint8 = 8
const EffectOpChmod uint8 = 9
const EffectOpChown uint8 = 10
const EffectOpMkdir uint8 = 11
const EffectOpRmdir uint8 = 12

// NETWORK
const EffectOpConnect uint8 = 1
const EffectOpBind uint8 = 2
const EffectOpSend uint8 = 3

// IPC
const EffectOpPipeWrite uint8 = 1
const EffectOpUnixWrite uint8 = 2
const EffectOpSysvShm uint8 = 3
const EffectOpSysvMsg uint8 = 4
const EffectOpSysvSem uint8 = 5
const EffectOpPosixMq uint8 = 6
const EffectOpSharedMapping uint8 = 7

// SIGNAL
const EffectOpKill uint8 = 1
const EffectOpPtrace uint8 = 2

// PRIVILEGE
const EffectOpExecPriv uint8 = 1
const EffectOpSetuid uint8 = 2
const EffectOpSetgid uint8 = 3
const EffectOpSetgroups uint8 = 4
const EffectOpCapset uint8 = 5

// OUTPUT
const EffectOpWriteOut uint8 = 1
const EffectOpSendfile uint8 = 2
const EffectOpSplice uint8 = 3
const EffectOpIoUring uint8 = 4

// SYSTEM
const EffectOpMount uint8 = 1
const EffectOpNamespace uint8 = 2
const EffectOpKeyring uint8 = 3
const EffectOpBpf uint8 = 4
const EffectOpPerf uint8 = 5
const EffectOpTtyIoctl uint8 = 6
const EffectOpProcessVm uint8 = 7

/* ---- sources ---- */
const EffectSourceFs uint8 = 0
const EffectSourceProc uint8 = 1
const EffectSourceNet uint8 = 2
const EffectSourceIpc uint8 = 3
const EffectSourcePrivilege uint8 = 4
const EffectSourceOutput uint8 = 5
const EffectSourceSystem uint8 = 6

/* ---- encoding ---- */
func EncodeEventType(cls uint8, op uint8) uint16 {
    return uint16(cls) | (uint16(op) << 8)
}
func EventClassOf(ty uint16) uint8 {
    return uint8(ty & 0xFF)
}
func EventOpOf(ty uint16) uint8 {
    return uint8((ty >> 8) & 0xFF)
}
